// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/issuer/issuer.proto

package issuer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	replicator "token-strike/tsp2p/replicator"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// LockTokenRequest send information about token
type LockTokenRequest struct {
	// token — token name
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// count — number of tokens to lock
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// htlc — hash of preimagine
	Htlc string `protobuf:"bytes,3,opt,name=htlc,proto3" json:"htlc,omitempty"`
	// recipient — wallet address of new owner of tokens
	Recipient string `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// proof_count — lock expiration time in PKT blocks
	ProofCount           int32    `protobuf:"varint,5,opt,name=proof_count,json=proofCount,proto3" json:"proof_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockTokenRequest) Reset()         { *m = LockTokenRequest{} }
func (m *LockTokenRequest) String() string { return proto.CompactTextString(m) }
func (*LockTokenRequest) ProtoMessage()    {}
func (*LockTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_868a71152c014334, []int{0}
}

func (m *LockTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockTokenRequest.Unmarshal(m, b)
}
func (m *LockTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockTokenRequest.Marshal(b, m, deterministic)
}
func (m *LockTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockTokenRequest.Merge(m, src)
}
func (m *LockTokenRequest) XXX_Size() int {
	return xxx_messageInfo_LockTokenRequest.Size(m)
}
func (m *LockTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockTokenRequest proto.InternalMessageInfo

func (m *LockTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LockTokenRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *LockTokenRequest) GetHtlc() string {
	if m != nil {
		return m.Htlc
	}
	return ""
}

func (m *LockTokenRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *LockTokenRequest) GetProofCount() int32 {
	if m != nil {
		return m.ProofCount
	}
	return 0
}

// LockTokenResponse response with hash of lock
type LockTokenResponse struct {
	// lock_id — hash of lock
	LockId               string   `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockTokenResponse) Reset()         { *m = LockTokenResponse{} }
func (m *LockTokenResponse) String() string { return proto.CompactTextString(m) }
func (*LockTokenResponse) ProtoMessage()    {}
func (*LockTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_868a71152c014334, []int{1}
}

func (m *LockTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockTokenResponse.Unmarshal(m, b)
}
func (m *LockTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockTokenResponse.Marshal(b, m, deterministic)
}
func (m *LockTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockTokenResponse.Merge(m, src)
}
func (m *LockTokenResponse) XXX_Size() int {
	return xxx_messageInfo_LockTokenResponse.Size(m)
}
func (m *LockTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LockTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LockTokenResponse proto.InternalMessageInfo

func (m *LockTokenResponse) GetLockId() string {
	if m != nil {
		return m.LockId
	}
	return ""
}

type TransferTokensRequest struct {
	// token — token name
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// count — number of tokens to lock
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// total price
	Amt int64 `protobuf:"varint,3,opt,name=amt,proto3" json:"amt,omitempty"`
	// recipient — wallet address of new owner of tokens
	Recipient string `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// proof_count — lock expiration time in PKT blocks
	ProofCount           int32    `protobuf:"varint,5,opt,name=proof_count,json=proofCount,proto3" json:"proof_count,omitempty"`
	Memo                 string   `protobuf:"bytes,6,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferTokensRequest) Reset()         { *m = TransferTokensRequest{} }
func (m *TransferTokensRequest) String() string { return proto.CompactTextString(m) }
func (*TransferTokensRequest) ProtoMessage()    {}
func (*TransferTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_868a71152c014334, []int{2}
}

func (m *TransferTokensRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferTokensRequest.Unmarshal(m, b)
}
func (m *TransferTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferTokensRequest.Marshal(b, m, deterministic)
}
func (m *TransferTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferTokensRequest.Merge(m, src)
}
func (m *TransferTokensRequest) XXX_Size() int {
	return xxx_messageInfo_TransferTokensRequest.Size(m)
}
func (m *TransferTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferTokensRequest proto.InternalMessageInfo

func (m *TransferTokensRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TransferTokensRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *TransferTokensRequest) GetAmt() int64 {
	if m != nil {
		return m.Amt
	}
	return 0
}

func (m *TransferTokensRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *TransferTokensRequest) GetProofCount() int32 {
	if m != nil {
		return m.ProofCount
	}
	return 0
}

func (m *TransferTokensRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

// SignTokenSellResponse — info about sign offer
type TransferTokensResponse struct {
	// lock_id — hash of lock
	LockId string `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	// htlc — hash of preimagine
	Htlc                 string   `protobuf:"bytes,2,opt,name=htlc,proto3" json:"htlc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferTokensResponse) Reset()         { *m = TransferTokensResponse{} }
func (m *TransferTokensResponse) String() string { return proto.CompactTextString(m) }
func (*TransferTokensResponse) ProtoMessage()    {}
func (*TransferTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_868a71152c014334, []int{3}
}

func (m *TransferTokensResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferTokensResponse.Unmarshal(m, b)
}
func (m *TransferTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferTokensResponse.Marshal(b, m, deterministic)
}
func (m *TransferTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferTokensResponse.Merge(m, src)
}
func (m *TransferTokensResponse) XXX_Size() int {
	return xxx_messageInfo_TransferTokensResponse.Size(m)
}
func (m *TransferTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransferTokensResponse proto.InternalMessageInfo

func (m *TransferTokensResponse) GetLockId() string {
	if m != nil {
		return m.LockId
	}
	return ""
}

func (m *TransferTokensResponse) GetHtlc() string {
	if m != nil {
		return m.Htlc
	}
	return ""
}

func init() {
	proto.RegisterType((*LockTokenRequest)(nil), "issuer.LockTokenRequest")
	proto.RegisterType((*LockTokenResponse)(nil), "issuer.LockTokenResponse")
	proto.RegisterType((*TransferTokensRequest)(nil), "issuer.TransferTokensRequest")
	proto.RegisterType((*TransferTokensResponse)(nil), "issuer.TransferTokensResponse")
}

func init() { proto.RegisterFile("protos/issuer/issuer.proto", fileDescriptor_868a71152c014334) }

var fileDescriptor_868a71152c014334 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xdd, 0xae, 0xd2, 0x40,
	0x10, 0x4e, 0xe9, 0xa1, 0x86, 0xf1, 0x27, 0xc7, 0x8d, 0x1e, 0x7b, 0x7a, 0x44, 0x9a, 0x5e, 0x71,
	0xa1, 0x6d, 0x82, 0x2f, 0x60, 0x24, 0xc4, 0x90, 0x90, 0x18, 0x2b, 0x57, 0xde, 0x10, 0x28, 0x03,
	0x6e, 0xfa, 0xb3, 0xeb, 0xee, 0xd6, 0xc4, 0xc7, 0xf0, 0x2d, 0x7c, 0x06, 0x9f, 0xce, 0xec, 0x6e,
	0x0b, 0x95, 0x40, 0x4c, 0x3c, 0x57, 0xcc, 0x7c, 0x33, 0x7c, 0x9d, 0xef, 0xeb, 0x57, 0x08, 0xb8,
	0x60, 0x8a, 0xc9, 0x84, 0x4a, 0x59, 0xa3, 0x68, 0x7e, 0x62, 0x03, 0x12, 0xcf, 0x76, 0xc1, 0xdd,
	0x9e, 0xb1, 0x7d, 0x81, 0x89, 0x41, 0x37, 0xf5, 0x2e, 0xc1, 0x92, 0xab, 0x1f, 0x76, 0x29, 0x88,
	0x1a, 0x02, 0x81, 0xbc, 0xa0, 0xd9, 0x5a, 0x31, 0xd1, 0x29, 0xed, 0x4e, 0xf4, 0xd3, 0x81, 0xeb,
	0x05, 0xcb, 0xf2, 0x25, 0xcb, 0xb1, 0x4a, 0xf1, 0x5b, 0x8d, 0x52, 0x91, 0x67, 0xd0, 0x57, 0xba,
	0xf7, 0x9d, 0xd0, 0x19, 0x0f, 0x52, 0xdb, 0x68, 0x34, 0x63, 0x75, 0xa5, 0xfc, 0x5e, 0xe8, 0x8c,
	0xdd, 0xd4, 0x36, 0x84, 0xc0, 0xd5, 0x57, 0x55, 0x64, 0xbe, 0x6b, 0x56, 0x4d, 0x4d, 0x5e, 0xc2,
	0x40, 0x60, 0x46, 0x39, 0xc5, 0x4a, 0xf9, 0x57, 0x66, 0x70, 0x04, 0xc8, 0x08, 0x1e, 0x72, 0xc1,
	0xd8, 0x6e, 0x65, 0xd9, 0xfa, 0xa1, 0x33, 0xee, 0xa7, 0x60, 0xa0, 0xa9, 0x46, 0xa2, 0xd7, 0xf0,
	0xb4, 0x73, 0x92, 0xe4, 0xac, 0x92, 0x48, 0x5e, 0xc0, 0x83, 0x82, 0x65, 0xf9, 0x8a, 0x6e, 0x9b,
	0xab, 0x3c, 0xdd, 0xce, 0xb7, 0xd1, 0x2f, 0x07, 0x9e, 0x2f, 0xc5, 0xba, 0x92, 0x3b, 0x14, 0xe6,
	0x2f, 0xf2, 0x7f, 0x64, 0x5c, 0x83, 0xbb, 0x2e, 0x95, 0x51, 0xe1, 0xa6, 0xba, 0xbc, 0xa7, 0x08,
	0xed, 0x4b, 0x89, 0x25, 0xf3, 0x3d, 0xeb, 0x8b, 0xae, 0xa3, 0x19, 0xdc, 0x9c, 0x5e, 0xfa, 0x0f,
	0x75, 0x07, 0x7b, 0x7b, 0x47, 0x7b, 0x27, 0xbf, 0x7b, 0xf0, 0x78, 0x6e, 0xde, 0xff, 0x67, 0x14,
	0xdf, 0x69, 0x86, 0xe4, 0x23, 0x3c, 0xf9, 0x9b, 0x98, 0x0c, 0xe3, 0x26, 0x2f, 0x67, 0xad, 0x09,
	0x5e, 0x5d, 0x1a, 0x37, 0xf7, 0x4c, 0x01, 0xcc, 0x13, 0x0c, 0x4c, 0x86, 0x71, 0x27, 0x37, 0x47,
	0xbc, 0x25, 0xbb, 0x89, 0x6d, 0x0a, 0xe3, 0x36, 0x85, 0xf1, 0x4c, 0xa7, 0x90, 0x7c, 0x82, 0x47,
	0x1f, 0x50, 0x99, 0xd5, 0x05, 0x95, 0x8a, 0x8c, 0xba, 0x34, 0xdd, 0x49, 0x4b, 0x14, 0x5e, 0x5e,
	0x68, 0xee, 0x7a, 0x07, 0x83, 0x43, 0x34, 0x88, 0xdf, 0x8a, 0x38, 0x0d, 0x70, 0x70, 0x7b, 0x66,
	0x62, 0x19, 0xde, 0xdf, 0x7d, 0xb9, 0x35, 0x39, 0x78, 0x23, 0x95, 0xa0, 0x39, 0x26, 0x4a, 0xf2,
	0x09, 0x6f, 0x3e, 0xae, 0x8d, 0x67, 0x14, 0xbc, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xe1,
	0x0f, 0x43, 0x7b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IssuerServiceClient is the client API for IssuerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IssuerServiceClient interface {
	// TransferTokens
	TransferTokens(ctx context.Context, in *TransferTokensRequest, opts ...grpc.CallOption) (*TransferTokensResponse, error)
	// IssueToken — Issue new token with given data. Request data equal to
	// token purchase data, because it is token offer.
	IssueToken(ctx context.Context, in *replicator.IssueTokenRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// GetTokenList — Return list of issued token with information about
	// expiration time and fix price.
	GetTokenList(ctx context.Context, in *replicator.GetTokenListRequest, opts ...grpc.CallOption) (*replicator.GetTokenListResponse, error)
	// LockToken — Return hash of lock token for verify htlc and information
	// about transaction
	LockToken(ctx context.Context, in *LockTokenRequest, opts ...grpc.CallOption) (*LockTokenResponse, error)
}

type issuerServiceClient struct {
	cc *grpc.ClientConn
}

func NewIssuerServiceClient(cc *grpc.ClientConn) IssuerServiceClient {
	return &issuerServiceClient{cc}
}

func (c *issuerServiceClient) TransferTokens(ctx context.Context, in *TransferTokensRequest, opts ...grpc.CallOption) (*TransferTokensResponse, error) {
	out := new(TransferTokensResponse)
	err := c.cc.Invoke(ctx, "/issuer.IssuerService/TransferTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerServiceClient) IssueToken(ctx context.Context, in *replicator.IssueTokenRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/issuer.IssuerService/IssueToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerServiceClient) GetTokenList(ctx context.Context, in *replicator.GetTokenListRequest, opts ...grpc.CallOption) (*replicator.GetTokenListResponse, error) {
	out := new(replicator.GetTokenListResponse)
	err := c.cc.Invoke(ctx, "/issuer.IssuerService/GetTokenList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerServiceClient) LockToken(ctx context.Context, in *LockTokenRequest, opts ...grpc.CallOption) (*LockTokenResponse, error) {
	out := new(LockTokenResponse)
	err := c.cc.Invoke(ctx, "/issuer.IssuerService/LockToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssuerServiceServer is the server API for IssuerService service.
type IssuerServiceServer interface {
	// TransferTokens
	TransferTokens(context.Context, *TransferTokensRequest) (*TransferTokensResponse, error)
	// IssueToken — Issue new token with given data. Request data equal to
	// token purchase data, because it is token offer.
	IssueToken(context.Context, *replicator.IssueTokenRequest) (*empty.Empty, error)
	// GetTokenList — Return list of issued token with information about
	// expiration time and fix price.
	GetTokenList(context.Context, *replicator.GetTokenListRequest) (*replicator.GetTokenListResponse, error)
	// LockToken — Return hash of lock token for verify htlc and information
	// about transaction
	LockToken(context.Context, *LockTokenRequest) (*LockTokenResponse, error)
}

// UnimplementedIssuerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIssuerServiceServer struct {
}

func (*UnimplementedIssuerServiceServer) TransferTokens(ctx context.Context, req *TransferTokensRequest) (*TransferTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferTokens not implemented")
}
func (*UnimplementedIssuerServiceServer) IssueToken(ctx context.Context, req *replicator.IssueTokenRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueToken not implemented")
}
func (*UnimplementedIssuerServiceServer) GetTokenList(ctx context.Context, req *replicator.GetTokenListRequest) (*replicator.GetTokenListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenList not implemented")
}
func (*UnimplementedIssuerServiceServer) LockToken(ctx context.Context, req *LockTokenRequest) (*LockTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockToken not implemented")
}

func RegisterIssuerServiceServer(s *grpc.Server, srv IssuerServiceServer) {
	s.RegisterService(&_IssuerService_serviceDesc, srv)
}

func _IssuerService_TransferTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServiceServer).TransferTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/issuer.IssuerService/TransferTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServiceServer).TransferTokens(ctx, req.(*TransferTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssuerService_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(replicator.IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServiceServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/issuer.IssuerService/IssueToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServiceServer).IssueToken(ctx, req.(*replicator.IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssuerService_GetTokenList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(replicator.GetTokenListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServiceServer).GetTokenList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/issuer.IssuerService/GetTokenList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServiceServer).GetTokenList(ctx, req.(*replicator.GetTokenListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssuerService_LockToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServiceServer).LockToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/issuer.IssuerService/LockToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServiceServer).LockToken(ctx, req.(*LockTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IssuerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "issuer.IssuerService",
	HandlerType: (*IssuerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferTokens",
			Handler:    _IssuerService_TransferTokens_Handler,
		},
		{
			MethodName: "IssueToken",
			Handler:    _IssuerService_IssueToken_Handler,
		},
		{
			MethodName: "GetTokenList",
			Handler:    _IssuerService_GetTokenList_Handler,
		},
		{
			MethodName: "LockToken",
			Handler:    _IssuerService_LockToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/issuer/issuer.proto",
}
