// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/tokenstrike/tokenstrike.proto

package tokenstrike

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	DB "token-strike/tsp2p/server/DB"
	lock "token-strike/tsp2p/server/lock"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// InvReq — meta information about data
type InvReq struct {
	// invs — collection of meta information with type, tokenID and hash of data
	Invs                 []*Inv   `protobuf:"bytes,1,rep,name=invs,proto3" json:"invs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvReq) Reset()         { *m = InvReq{} }
func (m *InvReq) String() string { return proto.CompactTextString(m) }
func (*InvReq) ProtoMessage()    {}
func (*InvReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da023b1b27b350a, []int{0}
}

func (m *InvReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvReq.Unmarshal(m, b)
}
func (m *InvReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvReq.Marshal(b, m, deterministic)
}
func (m *InvReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvReq.Merge(m, src)
}
func (m *InvReq) XXX_Size() int {
	return xxx_messageInfo_InvReq.Size(m)
}
func (m *InvReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InvReq.DiscardUnknown(m)
}

var xxx_messageInfo_InvReq proto.InternalMessageInfo

func (m *InvReq) GetInvs() []*Inv {
	if m != nil {
		return m.Invs
	}
	return nil
}

// Inv contains info about data that need replicates to other replicators
type Inv struct {
	// parent for block or lock, is the token id (hash block 0)
	// for new token notifications, the parent is the issuer
	Parent []byte `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// type — indicates what type of data will be sent
	Type uint32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	// entity_hash — hash of data
	EntityHash           []byte   `protobuf:"bytes,3,opt,name=entity_hash,json=entityHash,proto3" json:"entity_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inv) Reset()         { *m = Inv{} }
func (m *Inv) String() string { return proto.CompactTextString(m) }
func (*Inv) ProtoMessage()    {}
func (*Inv) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da023b1b27b350a, []int{1}
}

func (m *Inv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inv.Unmarshal(m, b)
}
func (m *Inv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inv.Marshal(b, m, deterministic)
}
func (m *Inv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inv.Merge(m, src)
}
func (m *Inv) XXX_Size() int {
	return xxx_messageInfo_Inv.Size(m)
}
func (m *Inv) XXX_DiscardUnknown() {
	xxx_messageInfo_Inv.DiscardUnknown(m)
}

var xxx_messageInfo_Inv proto.InternalMessageInfo

func (m *Inv) GetParent() []byte {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Inv) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Inv) GetEntityHash() []byte {
	if m != nil {
		return m.EntityHash
	}
	return nil
}

// InvResp — request with information about needed data
type InvResp struct {
	// needed — reflects the need for data
	Needed               []bool   `protobuf:"varint,1,rep,packed,name=needed,proto3" json:"needed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvResp) Reset()         { *m = InvResp{} }
func (m *InvResp) String() string { return proto.CompactTextString(m) }
func (*InvResp) ProtoMessage()    {}
func (*InvResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da023b1b27b350a, []int{2}
}

func (m *InvResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvResp.Unmarshal(m, b)
}
func (m *InvResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvResp.Marshal(b, m, deterministic)
}
func (m *InvResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvResp.Merge(m, src)
}
func (m *InvResp) XXX_Size() int {
	return xxx_messageInfo_InvResp.Size(m)
}
func (m *InvResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InvResp.DiscardUnknown(m)
}

var xxx_messageInfo_InvResp proto.InternalMessageInfo

func (m *InvResp) GetNeeded() []bool {
	if m != nil {
		return m.Needed
	}
	return nil
}

// Data — content needed to send
type Data struct {
	// Types that are valid to be assigned to Data:
	//	*Data_Lock
	//	*Data_Block
	//	*Data_Transfer
	Data                 isData_Data `protobuf_oneof:"data"`
	Token                string      `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da023b1b27b350a, []int{3}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

type isData_Data interface {
	isData_Data()
}

type Data_Lock struct {
	Lock *lock.Lock `protobuf:"bytes,1,opt,name=lock,proto3,oneof"`
}

type Data_Block struct {
	Block *DB.Block `protobuf:"bytes,2,opt,name=block,proto3,oneof"`
}

type Data_Transfer struct {
	Transfer *TransferTokens `protobuf:"bytes,3,opt,name=transfer,proto3,oneof"`
}

func (*Data_Lock) isData_Data() {}

func (*Data_Block) isData_Data() {}

func (*Data_Transfer) isData_Data() {}

func (m *Data) GetData() isData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Data) GetLock() *lock.Lock {
	if x, ok := m.GetData().(*Data_Lock); ok {
		return x.Lock
	}
	return nil
}

func (m *Data) GetBlock() *DB.Block {
	if x, ok := m.GetData().(*Data_Block); ok {
		return x.Block
	}
	return nil
}

func (m *Data) GetTransfer() *TransferTokens {
	if x, ok := m.GetData().(*Data_Transfer); ok {
		return x.Transfer
	}
	return nil
}

func (m *Data) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Data) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Data_Lock)(nil),
		(*Data_Block)(nil),
		(*Data_Transfer)(nil),
	}
}

// PostDataResp — contains information about warking with data
type PostDataResp struct {
	//  warning — collection of warnings each for own Inv
	Warning              []string `protobuf:"bytes,1,rep,name=warning,proto3" json:"warning,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostDataResp) Reset()         { *m = PostDataResp{} }
func (m *PostDataResp) String() string { return proto.CompactTextString(m) }
func (*PostDataResp) ProtoMessage()    {}
func (*PostDataResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da023b1b27b350a, []int{4}
}

func (m *PostDataResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostDataResp.Unmarshal(m, b)
}
func (m *PostDataResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostDataResp.Marshal(b, m, deterministic)
}
func (m *PostDataResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostDataResp.Merge(m, src)
}
func (m *PostDataResp) XXX_Size() int {
	return xxx_messageInfo_PostDataResp.Size(m)
}
func (m *PostDataResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PostDataResp.DiscardUnknown(m)
}

var xxx_messageInfo_PostDataResp proto.InternalMessageInfo

func (m *PostDataResp) GetWarning() []string {
	if m != nil {
		return m.Warning
	}
	return nil
}

// TransferTokens — information about transaction
type TransferTokens struct {
	// htlc — contract from lnd network
	Htlc []byte `protobuf:"bytes,1,opt,name=htlc,proto3" json:"htlc,omitempty"`
	// lock id
	Lock                 []byte   `protobuf:"bytes,2,opt,name=lock,proto3" json:"lock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferTokens) Reset()         { *m = TransferTokens{} }
func (m *TransferTokens) String() string { return proto.CompactTextString(m) }
func (*TransferTokens) ProtoMessage()    {}
func (*TransferTokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da023b1b27b350a, []int{5}
}

func (m *TransferTokens) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferTokens.Unmarshal(m, b)
}
func (m *TransferTokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferTokens.Marshal(b, m, deterministic)
}
func (m *TransferTokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferTokens.Merge(m, src)
}
func (m *TransferTokens) XXX_Size() int {
	return xxx_messageInfo_TransferTokens.Size(m)
}
func (m *TransferTokens) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferTokens.DiscardUnknown(m)
}

var xxx_messageInfo_TransferTokens proto.InternalMessageInfo

func (m *TransferTokens) GetHtlc() []byte {
	if m != nil {
		return m.Htlc
	}
	return nil
}

func (m *TransferTokens) GetLock() []byte {
	if m != nil {
		return m.Lock
	}
	return nil
}

// TokenStatusReq — status of which token is needed
type TokenStatusReq struct {
	// tokenid — generated from block0
	Tokenid              string   `protobuf:"bytes,1,opt,name=tokenid,proto3" json:"tokenid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenStatusReq) Reset()         { *m = TokenStatusReq{} }
func (m *TokenStatusReq) String() string { return proto.CompactTextString(m) }
func (*TokenStatusReq) ProtoMessage()    {}
func (*TokenStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da023b1b27b350a, []int{6}
}

func (m *TokenStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenStatusReq.Unmarshal(m, b)
}
func (m *TokenStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenStatusReq.Marshal(b, m, deterministic)
}
func (m *TokenStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenStatusReq.Merge(m, src)
}
func (m *TokenStatusReq) XXX_Size() int {
	return xxx_messageInfo_TokenStatusReq.Size(m)
}
func (m *TokenStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_TokenStatusReq proto.InternalMessageInfo

func (m *TokenStatusReq) GetTokenid() string {
	if m != nil {
		return m.Tokenid
	}
	return ""
}

// TokenStatus — information about token
type TokenStatus struct {
	// current_height — pkt height
	CurrentHeight uint32 `protobuf:"varint,1,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	// current_hash —  token id
	CurrentHash string `protobuf:"bytes,2,opt,name=current_hash,json=currentHash,proto3" json:"current_hash,omitempty"`
	// dblock0 — first block of chain
	Dblock0 *DB.Block `protobuf:"bytes,3,opt,name=dblock0,proto3" json:"dblock0,omitempty"`
	// state0 — state of first block
	State0               *DB.State `protobuf:"bytes,4,opt,name=state0,proto3" json:"state0,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TokenStatus) Reset()         { *m = TokenStatus{} }
func (m *TokenStatus) String() string { return proto.CompactTextString(m) }
func (*TokenStatus) ProtoMessage()    {}
func (*TokenStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da023b1b27b350a, []int{7}
}

func (m *TokenStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenStatus.Unmarshal(m, b)
}
func (m *TokenStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenStatus.Marshal(b, m, deterministic)
}
func (m *TokenStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenStatus.Merge(m, src)
}
func (m *TokenStatus) XXX_Size() int {
	return xxx_messageInfo_TokenStatus.Size(m)
}
func (m *TokenStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TokenStatus proto.InternalMessageInfo

func (m *TokenStatus) GetCurrentHeight() uint32 {
	if m != nil {
		return m.CurrentHeight
	}
	return 0
}

func (m *TokenStatus) GetCurrentHash() string {
	if m != nil {
		return m.CurrentHash
	}
	return ""
}

func (m *TokenStatus) GetDblock0() *DB.Block {
	if m != nil {
		return m.Dblock0
	}
	return nil
}

func (m *TokenStatus) GetState0() *DB.State {
	if m != nil {
		return m.State0
	}
	return nil
}

func init() {
	proto.RegisterType((*InvReq)(nil), "tokenstrike.InvReq")
	proto.RegisterType((*Inv)(nil), "tokenstrike.Inv")
	proto.RegisterType((*InvResp)(nil), "tokenstrike.InvResp")
	proto.RegisterType((*Data)(nil), "tokenstrike.Data")
	proto.RegisterType((*PostDataResp)(nil), "tokenstrike.PostDataResp")
	proto.RegisterType((*TransferTokens)(nil), "tokenstrike.TransferTokens")
	proto.RegisterType((*TokenStatusReq)(nil), "tokenstrike.TokenStatusReq")
	proto.RegisterType((*TokenStatus)(nil), "tokenstrike.TokenStatus")
}

func init() {
	proto.RegisterFile("protos/tokenstrike/tokenstrike.proto", fileDescriptor_7da023b1b27b350a)
}

var fileDescriptor_7da023b1b27b350a = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x51, 0x6f, 0x9b, 0x3c,
	0x14, 0x2d, 0x09, 0x25, 0xc9, 0x25, 0x41, 0xdf, 0xe7, 0x55, 0x1d, 0x63, 0x0f, 0xa3, 0xa8, 0xed,
	0xd0, 0xa4, 0xd1, 0x88, 0xbd, 0x74, 0xaf, 0x51, 0xa5, 0xa6, 0xd2, 0x1e, 0x26, 0xaf, 0x4f, 0x7b,
	0xa9, 0x9c, 0xe0, 0x15, 0x94, 0xc8, 0x50, 0xec, 0x66, 0xea, 0x4f, 0xda, 0xdf, 0xd8, 0x2f, 0x9b,
	0x7c, 0x0d, 0x19, 0xb4, 0xda, 0x0b, 0xf2, 0x3d, 0xe7, 0x18, 0x9f, 0x7b, 0xae, 0x0d, 0xa7, 0x55,
	0x5d, 0xaa, 0x52, 0x5e, 0xa8, 0x72, 0xc3, 0x85, 0x54, 0x75, 0xb1, 0xe1, 0xdd, 0x75, 0x82, 0x34,
	0x71, 0x3b, 0x50, 0xf0, 0xba, 0xd9, 0x72, 0xb5, 0x30, 0xca, 0x6c, 0x65, 0x54, 0xc1, 0x71, 0x43,
	0x6c, 0xcb, 0xf5, 0x06, 0x3f, 0x06, 0x8f, 0x12, 0x70, 0x6e, 0xc4, 0x8e, 0xf2, 0x07, 0x72, 0x0a,
	0x76, 0x21, 0x76, 0xd2, 0xb7, 0xc2, 0x61, 0xec, 0xa6, 0xff, 0x25, 0xdd, 0x93, 0xb4, 0x04, 0xd9,
	0x88, 0xc2, 0xf0, 0x46, 0xec, 0xc8, 0x31, 0x38, 0x15, 0xab, 0xb9, 0x50, 0xbe, 0x15, 0x5a, 0xf1,
	0x94, 0x36, 0x15, 0x21, 0x60, 0xab, 0xa7, 0x8a, 0xfb, 0x83, 0xd0, 0x8a, 0x67, 0x14, 0xd7, 0xe4,
	0x1d, 0xb8, 0x5c, 0xa8, 0x42, 0x3d, 0xdd, 0xe5, 0x4c, 0xe6, 0xfe, 0x10, 0x37, 0x80, 0x81, 0x96,
	0x4c, 0xe6, 0xd1, 0x09, 0x8c, 0xd0, 0x83, 0xac, 0xf4, 0x7f, 0x05, 0xe7, 0x19, 0xcf, 0xd0, 0xc6,
	0x98, 0x36, 0x55, 0xf4, 0xcb, 0x02, 0xfb, 0x8a, 0x29, 0x46, 0x42, 0xb0, 0xb5, 0x7b, 0x3c, 0xd6,
	0x4d, 0x21, 0xc1, 0x56, 0xbe, 0x94, 0xeb, 0xcd, 0xf2, 0x80, 0x22, 0x43, 0xce, 0xe1, 0x70, 0x85,
	0x92, 0x01, 0x4a, 0xbc, 0xa4, 0x0d, 0x62, 0xb1, 0x35, 0x32, 0x43, 0x93, 0xcf, 0x30, 0x56, 0x35,
	0x13, 0xf2, 0x07, 0xaf, 0xd1, 0x93, 0x9b, 0xbe, 0xed, 0xf5, 0x7c, 0xdb, 0x90, 0xb7, 0x88, 0x2d,
	0x0f, 0xe8, 0x5e, 0x4e, 0x8e, 0xe0, 0x10, 0x95, 0xbe, 0x1d, 0x5a, 0xf1, 0x84, 0x9a, 0x62, 0xe1,
	0x80, 0x9d, 0x31, 0xc5, 0xa2, 0x18, 0xa6, 0x5f, 0x4b, 0xa9, 0xb4, 0x5d, 0xec, 0xc9, 0x87, 0xd1,
	0x4f, 0x56, 0x8b, 0x42, 0xdc, 0x63, 0x53, 0x13, 0xda, 0x96, 0xd1, 0x25, 0x78, 0xfd, 0x53, 0x74,
	0x7e, 0xb9, 0xda, 0xae, 0x9b, 0x54, 0x71, 0xad, 0xb1, 0x7d, 0x3f, 0x53, 0xd3, 0x64, 0xf4, 0x01,
	0x3c, 0xdc, 0xf1, 0x4d, 0x31, 0xf5, 0x28, 0xf5, 0xf8, 0x7c, 0x18, 0xa1, 0x8d, 0x22, 0xc3, 0xcd,
	0x13, 0xda, 0x96, 0x3a, 0x3b, 0xb7, 0x23, 0x26, 0x67, 0xe0, 0xad, 0x1f, 0x6b, 0x3d, 0xae, 0xbb,
	0x9c, 0x17, 0xf7, 0xb9, 0x99, 0xe1, 0x8c, 0xce, 0x1a, 0x74, 0x89, 0x20, 0x39, 0x81, 0xe9, 0x5e,
	0xa6, 0xe7, 0x36, 0xc0, 0xbf, 0xba, 0xad, 0x88, 0xc9, 0x9c, 0xc4, 0x30, 0xca, 0x30, 0xcc, 0x79,
	0x93, 0xe0, 0xb3, 0xb0, 0x69, 0x4b, 0x93, 0x73, 0x70, 0xa4, 0x62, 0x8a, 0xcf, 0x31, 0xb2, 0xae,
	0x50, 0x9b, 0xe2, 0xb4, 0x61, 0xd3, 0xdf, 0x7f, 0xbd, 0xea, 0x21, 0x90, 0xb9, 0xb9, 0x6e, 0xaf,
	0x5e, 0xdc, 0x46, 0xfe, 0x10, 0x1c, 0xbd, 0x04, 0x65, 0x45, 0x2e, 0x61, 0xdc, 0xa6, 0x4f, 0xfe,
	0xef, 0x29, 0x34, 0x14, 0xbc, 0xe9, 0x41, 0xbd, 0x39, 0x5d, 0x83, 0x77, 0xcd, 0x55, 0x37, 0xa9,
	0x67, 0x17, 0xa2, 0x17, 0x78, 0xe0, 0xff, 0x8b, 0x5c, 0xbc, 0xff, 0x7e, 0x86, 0xd4, 0xc7, 0xf6,
	0xcd, 0xca, 0x2a, 0xad, 0x2e, 0x24, 0xaf, 0x77, 0xbc, 0xee, 0x3e, 0xe0, 0x95, 0x83, 0x6f, 0xf0,
	0xd3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0xa1, 0x58, 0xc3, 0xe9, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TokenStrikeClient is the client API for TokenStrike service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenStrikeClient interface {
	// Inv — send meta information to token strike
	Inv(ctx context.Context, in *InvReq, opts ...grpc.CallOption) (*InvResp, error)
	// PostData — send full data to replication
	PostData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*PostDataResp, error)
	// GetTokenStatus — response with information about token
	GetTokenStatus(ctx context.Context, in *TokenStatusReq, opts ...grpc.CallOption) (*TokenStatus, error)
}

type tokenStrikeClient struct {
	cc *grpc.ClientConn
}

func NewTokenStrikeClient(cc *grpc.ClientConn) TokenStrikeClient {
	return &tokenStrikeClient{cc}
}

func (c *tokenStrikeClient) Inv(ctx context.Context, in *InvReq, opts ...grpc.CallOption) (*InvResp, error) {
	out := new(InvResp)
	err := c.cc.Invoke(ctx, "/tokenstrike.TokenStrike/Inv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenStrikeClient) PostData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*PostDataResp, error) {
	out := new(PostDataResp)
	err := c.cc.Invoke(ctx, "/tokenstrike.TokenStrike/PostData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenStrikeClient) GetTokenStatus(ctx context.Context, in *TokenStatusReq, opts ...grpc.CallOption) (*TokenStatus, error) {
	out := new(TokenStatus)
	err := c.cc.Invoke(ctx, "/tokenstrike.TokenStrike/GetTokenStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenStrikeServer is the server API for TokenStrike service.
type TokenStrikeServer interface {
	// Inv — send meta information to token strike
	Inv(context.Context, *InvReq) (*InvResp, error)
	// PostData — send full data to replication
	PostData(context.Context, *Data) (*PostDataResp, error)
	// GetTokenStatus — response with information about token
	GetTokenStatus(context.Context, *TokenStatusReq) (*TokenStatus, error)
}

// UnimplementedTokenStrikeServer can be embedded to have forward compatible implementations.
type UnimplementedTokenStrikeServer struct {
}

func (*UnimplementedTokenStrikeServer) Inv(ctx context.Context, req *InvReq) (*InvResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inv not implemented")
}
func (*UnimplementedTokenStrikeServer) PostData(ctx context.Context, req *Data) (*PostDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostData not implemented")
}
func (*UnimplementedTokenStrikeServer) GetTokenStatus(ctx context.Context, req *TokenStatusReq) (*TokenStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenStatus not implemented")
}

func RegisterTokenStrikeServer(s *grpc.Server, srv TokenStrikeServer) {
	s.RegisterService(&_TokenStrike_serviceDesc, srv)
}

func _TokenStrike_Inv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStrikeServer).Inv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenstrike.TokenStrike/Inv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStrikeServer).Inv(ctx, req.(*InvReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenStrike_PostData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStrikeServer).PostData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenstrike.TokenStrike/PostData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStrikeServer).PostData(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenStrike_GetTokenStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStrikeServer).GetTokenStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenstrike.TokenStrike/GetTokenStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStrikeServer).GetTokenStatus(ctx, req.(*TokenStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenStrike_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tokenstrike.TokenStrike",
	HandlerType: (*TokenStrikeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Inv",
			Handler:    _TokenStrike_Inv_Handler,
		},
		{
			MethodName: "PostData",
			Handler:    _TokenStrike_PostData_Handler,
		},
		{
			MethodName: "GetTokenStatus",
			Handler:    _TokenStrike_GetTokenStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/tokenstrike/tokenstrike.proto",
}
