// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/justifications/justifications.proto

package justifications

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	lock "token-strike/tsp2p/lock"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// LockToken the token locking
type LockToken struct {
	// lock — information about lock
	Lock                 *lock.Lock `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LockToken) Reset()         { *m = LockToken{} }
func (m *LockToken) String() string { return proto.CompactTextString(m) }
func (*LockToken) ProtoMessage()    {}
func (*LockToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee571a5de13873a7, []int{0}
}

func (m *LockToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockToken.Unmarshal(m, b)
}
func (m *LockToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockToken.Marshal(b, m, deterministic)
}
func (m *LockToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockToken.Merge(m, src)
}
func (m *LockToken) XXX_Size() int {
	return xxx_messageInfo_LockToken.Size(m)
}
func (m *LockToken) XXX_DiscardUnknown() {
	xxx_messageInfo_LockToken.DiscardUnknown(m)
}

var xxx_messageInfo_LockToken proto.InternalMessageInfo

func (m *LockToken) GetLock() *lock.Lock {
	if m != nil {
		return m.Lock
	}
	return nil
}

// TranferToken receiving funds for tokens and unlcok them
type TranferToken struct {
	// htlc_secret — htlc genereted issuer
	HtlcSecret string `protobuf:"bytes,1,opt,name=htlc_secret,json=htlcSecret,proto3" json:"htlc_secret,omitempty"`
	// lock — hash information about lock
	Lock                 string   `protobuf:"bytes,2,opt,name=lock,proto3" json:"lock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranferToken) Reset()         { *m = TranferToken{} }
func (m *TranferToken) String() string { return proto.CompactTextString(m) }
func (*TranferToken) ProtoMessage()    {}
func (*TranferToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee571a5de13873a7, []int{1}
}

func (m *TranferToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranferToken.Unmarshal(m, b)
}
func (m *TranferToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranferToken.Marshal(b, m, deterministic)
}
func (m *TranferToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranferToken.Merge(m, src)
}
func (m *TranferToken) XXX_Size() int {
	return xxx_messageInfo_TranferToken.Size(m)
}
func (m *TranferToken) XXX_DiscardUnknown() {
	xxx_messageInfo_TranferToken.DiscardUnknown(m)
}

var xxx_messageInfo_TranferToken proto.InternalMessageInfo

func (m *TranferToken) GetHtlcSecret() string {
	if m != nil {
		return m.HtlcSecret
	}
	return ""
}

func (m *TranferToken) GetLock() string {
	if m != nil {
		return m.Lock
	}
	return ""
}

// LockTimeOver timeout for token locking
type LockTimeOver struct {
	// proof_elapsed — PKT block hash confirming expiration lock
	ProofElapsed string `protobuf:"bytes,1,opt,name=proof_elapsed,json=proofElapsed,proto3" json:"proof_elapsed,omitempty"`
	// lock_id — hash with information about lock justification
	Lock                 string   `protobuf:"bytes,2,opt,name=lock,proto3" json:"lock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockTimeOver) Reset()         { *m = LockTimeOver{} }
func (m *LockTimeOver) String() string { return proto.CompactTextString(m) }
func (*LockTimeOver) ProtoMessage()    {}
func (*LockTimeOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee571a5de13873a7, []int{2}
}

func (m *LockTimeOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockTimeOver.Unmarshal(m, b)
}
func (m *LockTimeOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockTimeOver.Marshal(b, m, deterministic)
}
func (m *LockTimeOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockTimeOver.Merge(m, src)
}
func (m *LockTimeOver) XXX_Size() int {
	return xxx_messageInfo_LockTimeOver.Size(m)
}
func (m *LockTimeOver) XXX_DiscardUnknown() {
	xxx_messageInfo_LockTimeOver.DiscardUnknown(m)
}

var xxx_messageInfo_LockTimeOver proto.InternalMessageInfo

func (m *LockTimeOver) GetProofElapsed() string {
	if m != nil {
		return m.ProofElapsed
	}
	return ""
}

func (m *LockTimeOver) GetLock() string {
	if m != nil {
		return m.Lock
	}
	return ""
}

// Genesis initial block justification
type Genesis struct {
	// token — token identification by name
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Genesis) Reset()         { *m = Genesis{} }
func (m *Genesis) String() string { return proto.CompactTextString(m) }
func (*Genesis) ProtoMessage()    {}
func (*Genesis) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee571a5de13873a7, []int{3}
}

func (m *Genesis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Genesis.Unmarshal(m, b)
}
func (m *Genesis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Genesis.Marshal(b, m, deterministic)
}
func (m *Genesis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Genesis.Merge(m, src)
}
func (m *Genesis) XXX_Size() int {
	return xxx_messageInfo_Genesis.Size(m)
}
func (m *Genesis) XXX_DiscardUnknown() {
	xxx_messageInfo_Genesis.DiscardUnknown(m)
}

var xxx_messageInfo_Genesis proto.InternalMessageInfo

func (m *Genesis) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*LockToken)(nil), "justifications.LockToken")
	proto.RegisterType((*TranferToken)(nil), "justifications.TranferToken")
	proto.RegisterType((*LockTimeOver)(nil), "justifications.LockTimeOver")
	proto.RegisterType((*Genesis)(nil), "justifications.Genesis")
}

func init() {
	proto.RegisterFile("protos/justifications/justifications.proto", fileDescriptor_ee571a5de13873a7)
}

var fileDescriptor_ee571a5de13873a7 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xc7, 0xa9, 0xf8, 0x41, 0xa7, 0xab, 0x87, 0x20, 0x22, 0x1e, 0xac, 0xb6, 0x17, 0x51, 0x6c,
	0xa1, 0xbe, 0x81, 0x22, 0xbd, 0x08, 0x42, 0xed, 0xc9, 0x4b, 0x59, 0xe3, 0x2c, 0xc6, 0xac, 0x99,
	0x90, 0x19, 0x7d, 0x7e, 0xc9, 0x24, 0x17, 0x8b, 0x97, 0x90, 0xf9, 0xfd, 0x3f, 0x12, 0x06, 0xae,
	0x63, 0x22, 0x21, 0x9e, 0x7f, 0x7e, 0xb3, 0xb8, 0xce, 0xd9, 0x56, 0x1c, 0x85, 0xed, 0x71, 0xa6,
	0x26, 0x73, 0xf4, 0x97, 0x9e, 0x9d, 0xd4, 0x6c, 0x4f, 0xd6, 0xeb, 0x51, 0x7c, 0x93, 0x1b, 0x18,
	0x3e, 0x91, 0xf5, 0x6b, 0xf2, 0x18, 0xcc, 0x39, 0xec, 0x66, 0xe9, 0x74, 0x70, 0x31, 0xb8, 0x1a,
	0x2d, 0x60, 0xa6, 0xbe, 0x2c, 0xaf, 0x94, 0x4f, 0x1e, 0xa0, 0x59, 0xa7, 0x36, 0x74, 0x98, 0x8a,
	0x7f, 0x0c, 0xa3, 0x0f, 0xe9, 0xed, 0x86, 0xd1, 0x26, 0x14, 0x8d, 0x0d, 0x57, 0x90, 0xd1, 0x8b,
	0x12, 0x63, 0x6a, 0xe1, 0x8e, 0x2a, 0xa5, 0x64, 0x09, 0x8d, 0xbe, 0xe8, 0xbe, 0xf0, 0xf9, 0x07,
	0x93, 0x99, 0xc2, 0x61, 0x4c, 0x44, 0xdd, 0x06, 0xfb, 0x36, 0x32, 0xbe, 0xd7, 0x9a, 0x46, 0xe1,
	0x63, 0x61, 0xff, 0x16, 0x8d, 0xe1, 0x60, 0x89, 0x01, 0xd9, 0xb1, 0x39, 0x86, 0x3d, 0xc9, 0x3f,
	0xaa, 0xd9, 0x32, 0xdc, 0x4f, 0x5f, 0x2f, 0xf5, 0x72, 0xcb, 0x92, 0x9c, 0xc7, 0xb9, 0x70, 0x5c,
	0xc4, 0xad, 0x75, 0xbd, 0xed, 0xeb, 0x1e, 0xee, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x29, 0xae,
	0x61, 0xf9, 0x5d, 0x01, 0x00, 0x00,
}
